### PR TITLE
made plugin compatible with Webpack 4

### PR DESCRIPTION
**Pull request by sherlock1982**
These are the fixes to make plugin compatible with Webpack 4.
I made some changes to tests but still not able to complete everything but fixes looks ok so far.
That should close https://github.com/numical/script-ext-html-webpack-plugin/issues/41

### CODE REVIEW

**Comment by sherlock1982** [comment]
Almost there though I have no idea what is handlebars and why test fails there.

**Comment by sherlock1982** [comment]
Handlebars test will fail until handlebars loader is fixed

**Comment by numical** [comment]
@sherlock1982 - thanks so much for this - I am going to take a look now.
Sorry it has taken me so long to review.

**Comment by numical** [comment]
@sherlock1982 - I ran through your changes one by one so I that understood them and copied/modified as appropriate.  Noe that by setting the webpack mode to 'production' I got rid of some of the fiddly stuff around async chunk naming.  
All changes in v.2.0.0 - thank you very much.

**Comment by xanderiel** [comment]
Thanks @sherlock1982 and @numical. Entire code didn't compile – now it does. Saved my weekend.

**Pull request closed without merging**
